#!/usr/bin/env bash
## Install web server - Nginx.
##-----------------------------
## Run sudo update.
sudo apt-get -y update
## Install nginx.
sudo apt-get -y install nginx

## Allow nginx on firewall
sudo service nginx startsudo ufw allow 'Nginx HTTP'

## Change User /var/www
sudo chown -R "USER":"USER" /var/www/html
sudo chmod -R 755 /var/www

## Change file default --> index.html to nginx.
echo "Hello World!" > /var/www/html/index.nginx-debian.html
## Service nginx - start.
sudo service nginx start
