#!/usr/bin/env bash
## Redirecting to another page (The redirection must be a “301 Moved Permanently”)
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
## Service nginx - restart.
sudo service nginx restart
