#!/usr/bin/env bash
## Redirecting to another page (The page must return an HTTP 404 error code)
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
## Service nginx - restart.
sudo service nginx restart
